version: '3.3'
networks:
  default:  
    name: 'proxy_network'
services:
  alist:
    container_name: alist
    image: 'xhofe/alist:latest'
    restart: unless-stopped
    volumes:  
      - '/etc/alist:/opt/alist/data'
    ports:
            - '5244:5244'
    environment:
            - PUID=0
            - PGID=0
            - UMASK=022
    labels:   
      caddy: file.bibica.net
      caddy.reverse_proxy: "* {{upstreams 5244}}"
  caddy:
    image: "lucaslorentz/caddy-docker-proxy:ci-alpine"
    ports:    
      - "80:80" 
      - "443:443"
    volumes:  
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/caddy/:/data
    restart: unless-stopped
    environment:
      - CADDY_INGRESS_NETWORKS=proxy_network
